-- Insert de tabla TIPO_USUARIO
INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_USUARIO.NEXTVAL, 
'ADMINISTRADOR', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_USUARIO.NEXTVAL, 
'SUPERVISOR', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_USUARIO.NEXTVAL, 
'CAPTURISTA', 0, 'USUARIO', SYSDATE);

-- Insert de tabla TIPO_INVENTARIO
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'LIBRO', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'NOVELA', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'RELATO', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'MANUAL', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'GUÍA', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'LIBRO DE BOLSILLO', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'CUADERNO', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'ÁLBUM', 0, 'USUARIO', SYSDATE);
INSERT INTO TIPO_INVENTARIO (ID_TIPO_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_TIPO_INVENTARIO.NEXTVAL,
'EBOOK', 0, 'USUARIO', SYSDATE);

-- Insert de tabla ESTATUS_PRESTAMO
INSERT INTO ESTATUS_PRESTAMO (ID_ESTATUS_PRESTAMO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_ESTATUS_PRESTAMO.NEXTVAL,
'SOLICITADO', 0, 'USUARIO', SYSDATE);
INSERT INTO ESTATUS_PRESTAMO (ID_ESTATUS_PRESTAMO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_ESTATUS_PRESTAMO.NEXTVAL,
'REALIZADO', 0, 'USUARIO', SYSDATE);
INSERT INTO ESTATUS_PRESTAMO (ID_ESTATUS_PRESTAMO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_ESTATUS_PRESTAMO.NEXTVAL,
'CONCLUIDO', 0, 'USUARIO', SYSDATE);

-- Insert de tabla ESTATUS_DEVOLUCION
INSERT INTO ESTATUS_DEVOLUCION (ID_ESTATUS_DEVOLUCION, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_ESTATUS_DEVOLUCION.NEXTVAL,
'PENDIENTE', 0, 'USUARIO', SYSDATE);
INSERT INTO ESTATUS_DEVOLUCION (ID_ESTATUS_DEVOLUCION, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_ESTATUS_DEVOLUCION.NEXTVAL,
'ENTREGADO', 0, 'USUARIO', SYSDATE);

-- Insert de tabla CATEGORIA_INVENTARIO
INSERT INTO CATEGORIA_INVENTARIO (ID_CATEGORIA_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_CATEGORIA_INVENTARIO.NEXTVAL,
'FICCIÓN', 0, 'USUARIO', SYSDATE);
INSERT INTO CATEGORIA_INVENTARIO (ID_CATEGORIA_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_CATEGORIA_INVENTARIO.NEXTVAL,
'NO FICCIÓN', 0, 'USUARIO', SYSDATE);
INSERT INTO CATEGORIA_INVENTARIO (ID_CATEGORIA_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_CATEGORIA_INVENTARIO.NEXTVAL,
'INFANTILES', 0, 'USUARIO', SYSDATE);
INSERT INTO CATEGORIA_INVENTARIO (ID_CATEGORIA_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_CATEGORIA_INVENTARIO.NEXTVAL,
'JUVENILES', 0, 'USUARIO', SYSDATE);
INSERT INTO CATEGORIA_INVENTARIO (ID_CATEGORIA_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_CATEGORIA_INVENTARIO.NEXTVAL,
'COMICS', 0, 'USUARIO', SYSDATE);
INSERT INTO CATEGORIA_INVENTARIO (ID_CATEGORIA_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_CATEGORIA_INVENTARIO.NEXTVAL,
'MANGA', 0, 'USUARIO', SYSDATE);
INSERT INTO CATEGORIA_INVENTARIO (ID_CATEGORIA_INVENTARIO, DESCRIPCION, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_CATEGORIA_INVENTARIO.NEXTVAL,
'VARIOS', 0, 'USUARIO', SYSDATE);

-- Insert de tabla COSTOS_MULTA
INSERT INTO COSTOS_MULTA (ID_COSTO_MULTA, NUMERO_DIAS, COSTO, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_COSTO_MULTA.NEXTVAL, 1, 5, 0,
'USUARIO', SYSDATE);
INSERT INTO COSTOS_MULTA (ID_COSTO_MULTA, NUMERO_DIAS, COSTO, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_COSTO_MULTA.NEXTVAL, 2, 8, 0,
'USUARIO', SYSDATE);
INSERT INTO COSTOS_MULTA (ID_COSTO_MULTA, NUMERO_DIAS, COSTO, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_COSTO_MULTA.NEXTVAL, 3, 10, 0,
'USUARIO', SYSDATE);
INSERT INTO COSTOS_MULTA (ID_COSTO_MULTA, NUMERO_DIAS, COSTO, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_COSTO_MULTA.NEXTVAL, 4, 12, 0,
'USUARIO', SYSDATE);
INSERT INTO COSTOS_MULTA (ID_COSTO_MULTA, NUMERO_DIAS, COSTO, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_COSTO_MULTA.NEXTVAL, 5, 15, 0,
'USUARIO', SYSDATE);
INSERT INTO COSTOS_MULTA (ID_COSTO_MULTA, NUMERO_DIAS, COSTO, ESTATUSREGISTRO,
USUARIOCREACION, FECHACREACION) VALUES (SEQ_ID_COSTO_MULTA.NEXTVAL, 6, 20, 0,
'USUARIO', SYSDATE);