-- 1. Crear el usuario 
CREATE USER javapoo IDENTIFIED BY java
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

-- 2. Dar privilegios básicos para conectarse y trabajar con sus tablas
GRANT CREATE SESSION TO javapoo ;
GRANT CREATE TABLE TO javapoo ;
GRANT CREATE SEQUENCE TO javapoo ;
GRANT CREATE VIEW TO javapoo ;

-- ================================================
-- Ahora conectarse con el nuevo usuario (con SQL Developer):
-- ================================================

-- 3. Crear una tabla con el usuario
CREATE TABLE clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR2(100) NOT NULL,
    correo     VARCHAR2(150) UNIQUE,
    fecha_reg  DATE DEFAULT SYSDATE
);

-- 4. Insertar un registro de prueba
INSERT INTO clientes (nombre, correo) 
VALUES ('Carlos Sánchez', 'carlos@email.com');

COMMIT;

-- 5. Probar select
SELECT * FROM clientes;