-- Secuencias

CREATE SEQUENCE SEQ_ID_CATEGORIA_INVENTARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_COSTO_MULTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_ESTATUS_DEVOLUCION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_ESTATUS_PRESTAMO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_TIPO_INVENTARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_TIPO_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

