-- Secuencia de ejemplo 
-- CREATE SEQUENCE SEC_EJEMPLO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- SELECT SEC_EJEMPLO.NEXTVAL FROM DUAL;

-- Creación Secuencias para las llaves primarias (PK´s)
CREATE SEQUENCE SEC_ID_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_TELEFONO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_FACTURA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_PAGO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEC_ID_CLIENTE_BIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_TELEFONO_BIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_FACTURA_BIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEC_ID_PAGO_BIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
