-- Tabla TIPO_INVENTARIO
CREATE TABLE TIPO_INVENTARIO (
  ID_TIPO_INVENTARIO NUMBER NOT NULL,
  DESCRIPCION VARCHAR2 (30) NOT NULL,
  ESTATUSREGISTRO NUMBER NOT NULL,
  USUARIOCREACION VARCHAR2(100) NOT NULL,
  FECHACREACION DATE DEFAULT SYSDATE,
  USUARIOMODIFICACION VARCHAR2(100),
  FECHAMODIFICACION DATE,
  OBSREGISTRO VARCHAR2(100),
  CONSTRAINT pk_id_tipo_inventario_tipo_inventario PRIMARY KEY (ID_TIPO_INVENTARIO)
);
COMMENT ON TABLE TIPO_INVENTARIO IS 'Tabla de Catálogo de Tipo de Inventario';
COMMENT ON COLUMN TIPO_INVENTARIO.ID_TIPO_INVENTARIO IS 'Llave Primaria de la tabla Catálogo Tipo de Inventario';
COMMENT ON COLUMN TIPO_INVENTARIO.DESCRIPCION IS 'Descripción del Tipo de Inventario';
COMMENT ON COLUMN TIPO_INVENTARIO.ESTATUSREGISTRO IS 'Bandera que indica si el registro es valido, 0 (cero) es valido, 99 invalido';
COMMENT ON COLUMN TIPO_INVENTARIO.USUARIOCREACION IS 'Usuario Creación del Registro';
COMMENT ON COLUMN TIPO_INVENTARIO.FECHACREACION IS 'Fecha Creación del Registro';
COMMENT ON COLUMN TIPO_INVENTARIO.USUARIOMODIFICACION IS 'Usuario de Modificación del Registro';
COMMENT ON COLUMN TIPO_INVENTARIO.FECHAMODIFICACION IS 'Fecha de Modificación del Registro';
COMMENT ON COLUMN TIPO_INVENTARIO.OBSREGISTRO IS 'Observaciones del Registro';

-- Tabla CATEGORIA_INVENTARIO
CREATE TABLE CATEGORIA_INVENTARIO (
  ID_CATEGORIA_INVENTARIO NUMBER NOT NULL,
  DESCRIPCION VARCHAR2 (30) NOT NULL,
  ESTATUSREGISTRO NUMBER NOT NULL,
  USUARIOCREACION VARCHAR2(100) NOT NULL,
  FECHACREACION DATE DEFAULT SYSDATE,
  USUARIOMODIFICACION VARCHAR2(100),
  FECHAMODIFICACION DATE,
  OBSREGISTRO VARCHAR2(100),
  CONSTRAINT pk_id_categoria_inventario_categoria_inventario PRIMARY KEY (ID_CATEGORIA_INVENTARIO)
);
COMMENT ON TABLE CATEGORIA_INVENTARIO IS 'Tabla de Catálogo de Categoría de Inventario';
COMMENT ON COLUMN CATEGORIA_INVENTARIO.ID_CATEGORIA_INVENTARIO IS 'Llave Primaria de la tabla Catálogo Categoría de Inventario';
COMMENT ON COLUMN CATEGORIA_INVENTARIO.DESCRIPCION IS 'Descripción de la Categoría de Inventario';
COMMENT ON COLUMN CATEGORIA_INVENTARIO.ESTATUSREGISTRO IS 'Bandera que indica si el registro es valido, 0 (cero) es valido, 99 invalido';
COMMENT ON COLUMN CATEGORIA_INVENTARIO.USUARIOCREACION IS 'Usuario Creación del Registro';
COMMENT ON COLUMN CATEGORIA_INVENTARIO.FECHACREACION IS 'Fecha Creación del Registro';
COMMENT ON COLUMN CATEGORIA_INVENTARIO.USUARIOMODIFICACION IS 'Usuario de Modificación del Registro';
COMMENT ON COLUMN CATEGORIA_INVENTARIO.FECHAMODIFICACION IS 'Fecha de Modificación del Registro';
COMMENT ON COLUMN CATEGORIA_INVENTARIO.OBSREGISTRO IS 'Observaciones del Registro';

-- Tabla ESTATUS_PRESTAMO
CREATE TABLE ESTATUS_PRESTAMO (
  ID_ESTATUS_PRESTAMO NUMBER NOT NULL,
  DESCRIPCION VARCHAR2 (30) NOT NULL,
  ESTATUSREGISTRO NUMBER NOT NULL,
  USUARIOCREACION VARCHAR2(100) NOT NULL,
  FECHACREACION DATE DEFAULT SYSDATE,
  USUARIOMODIFICACION VARCHAR2(100),
  FECHAMODIFICACION DATE,
  OBSREGISTRO VARCHAR2(100),
  CONSTRAINT pk_id_estatus_prestamo_estatus_prestamo PRIMARY KEY (ID_ESTATUS_PRESTAMO)
);
COMMENT ON TABLE ESTATUS_PRESTAMO IS 'Tabla de Catálogo de Estatus de Prestamo';
COMMENT ON COLUMN ESTATUS_PRESTAMO.ID_ESTATUS_PRESTAMO IS 'Llave Primaria de la tabla Catálogo Estatus de Prestamo';
COMMENT ON COLUMN ESTATUS_PRESTAMO.DESCRIPCION IS 'Descripción del Estatus del Prestamo';
COMMENT ON COLUMN ESTATUS_PRESTAMO.ESTATUSREGISTRO IS 'Bandera que indica si el registro es valido, 0 (cero) es valido, 99 invalido';
COMMENT ON COLUMN ESTATUS_PRESTAMO.USUARIOCREACION IS 'Usuario Creación del Registro';
COMMENT ON COLUMN ESTATUS_PRESTAMO.FECHACREACION IS 'Fecha Creación del Registro';
COMMENT ON COLUMN ESTATUS_PRESTAMO.USUARIOMODIFICACION IS 'Usuario de Modificación del Registro';
COMMENT ON COLUMN ESTATUS_PRESTAMO.FECHAMODIFICACION IS 'Fecha de Modificación del Registro';
COMMENT ON COLUMN ESTATUS_PRESTAMO.OBSREGISTRO IS 'Observaciones del Registro';

-- Tabla ESTATUS_DEVOLUCION
CREATE TABLE ESTATUS_DEVOLUCION (
  ID_ESTATUS_DEVOLUCION NUMBER NOT NULL,
  DESCRIPCION VARCHAR2 (30) NOT NULL,
  ESTATUSREGISTRO NUMBER NOT NULL,
  USUARIOCREACION VARCHAR2(100) NOT NULL,
  FECHACREACION DATE DEFAULT SYSDATE,
  USUARIOMODIFICACION VARCHAR2(100),
  FECHAMODIFICACION DATE,
  OBSREGISTRO VARCHAR2(100),
  CONSTRAINT pk_id_estatus_devolucion_estatus_devolucion PRIMARY KEY (ID_ESTATUS_DEVOLUCION)
);
COMMENT ON TABLE ESTATUS_DEVOLUCION IS 'Tabla de Catálogo de Estatus de Devolución';
COMMENT ON COLUMN ESTATUS_DEVOLUCION.ID_ESTATUS_DEVOLUCION IS 'Llave Primaria de la tabla Catálogo Estatus de Devolución';
COMMENT ON COLUMN ESTATUS_DEVOLUCION.DESCRIPCION IS 'Descripción del Estatus de Devolución';
COMMENT ON COLUMN ESTATUS_DEVOLUCION.ESTATUSREGISTRO IS 'Bandera que indica si el registro es valido, 0 (cero) es valido, 99 invalido';
COMMENT ON COLUMN ESTATUS_DEVOLUCION.USUARIOCREACION IS 'Usuario Creación del Registro';
COMMENT ON COLUMN ESTATUS_DEVOLUCION.FECHACREACION IS 'Fecha Creación del Registro';
COMMENT ON COLUMN ESTATUS_DEVOLUCION.USUARIOMODIFICACION IS 'Usuario de Modificación del Registro';
COMMENT ON COLUMN ESTATUS_DEVOLUCION.FECHAMODIFICACION IS 'Fecha de Modificación del Registro';
COMMENT ON COLUMN ESTATUS_DEVOLUCION.OBSREGISTRO IS 'Observaciones del Registro';

-- Tabla TIPO_USUARIO
CREATE TABLE TIPO_USUARIO (
  ID_TIPO_USUARIO NUMBER NOT NULL,
  DESCRIPCION VARCHAR2 (30) NOT NULL,
  ESTATUSREGISTRO NUMBER NOT NULL,
  USUARIOCREACION VARCHAR2(100) NOT NULL,
  FECHACREACION DATE DEFAULT SYSDATE,
  USUARIOMODIFICACION VARCHAR2(100),
  FECHAMODIFICACION DATE,
  OBSREGISTRO VARCHAR2(100),
  CONSTRAINT pk_id_tipo_usuario_tipo_usuario PRIMARY KEY (ID_TIPO_USUARIO)
);
COMMENT ON TABLE TIPO_USUARIO IS 'Tabla de Catálogo de Tipos de Usuarios';
COMMENT ON COLUMN TIPO_USUARIO.ID_TIPO_USUARIO IS 'Llave Primaria de la tabla Catálogo de Tipos de Usuarios';
COMMENT ON COLUMN TIPO_USUARIO.DESCRIPCION IS 'Descripción del Tipo de Usuario';
COMMENT ON COLUMN TIPO_USUARIO.ESTATUSREGISTRO IS 'Bandera que indica si el registro es valido, 0 (cero) es valido, 99 invalido';
COMMENT ON COLUMN TIPO_USUARIO.USUARIOCREACION IS 'Usuario Creación del Registro';
COMMENT ON COLUMN TIPO_USUARIO.FECHACREACION IS 'Fecha Creación del Registro';
COMMENT ON COLUMN TIPO_USUARIO.USUARIOMODIFICACION IS 'Usuario de Modificación del Registro';
COMMENT ON COLUMN TIPO_USUARIO.FECHAMODIFICACION IS 'Fecha de Modificación del Registro';
COMMENT ON COLUMN TIPO_USUARIO.OBSREGISTRO IS 'Observaciones del Registro';

-- Tabla COSTOS_MULTA
CREATE TABLE COSTOS_MULTA (
  ID_COSTO_MULTA NUMBER NOT NULL,
  NUMERO_DIAS NUMBER NOT NULL,
  COSTO NUMBER (10,2) NOT NULL,
  ESTATUSREGISTRO NUMBER NOT NULL,
  USUARIOCREACION VARCHAR2(100) NOT NULL,
  FECHACREACION DATE DEFAULT SYSDATE,
  USUARIOMODIFICACION VARCHAR2(100),
  FECHAMODIFICACION DATE,
  OBSREGISTRO VARCHAR2(100),
  CONSTRAINT pk_id_costo_multa_costos_multa PRIMARY KEY (ID_COSTO_MULTA)
);
COMMENT ON TABLE COSTOS_MULTA IS 'Tabla de Catálogo que contiene los Costos de Multas por Días';
COMMENT ON COLUMN COSTOS_MULTA.ID_COSTO_MULTA IS 'Llave Primaria de la tabla Catálogo de Costos de Multas por Días';
COMMENT ON COLUMN COSTOS_MULTA.NUMERO_DIAS IS 'Número de Día para el Costo de Multa';
COMMENT ON COLUMN COSTOS_MULTA.COSTO IS 'Costo de Multa por Número de Días';
COMMENT ON COLUMN COSTOS_MULTA.ESTATUSREGISTRO IS 'Bandera que indica si el registro es valido, 0 (cero) es valido, 99 invalido';
COMMENT ON COLUMN COSTOS_MULTA.USUARIOCREACION IS 'Usuario Creación del Registro';
COMMENT ON COLUMN COSTOS_MULTA.FECHACREACION IS 'Fecha Creación del Registro';
COMMENT ON COLUMN COSTOS_MULTA.USUARIOMODIFICACION IS 'Usuario de Modificación del Registro';
COMMENT ON COLUMN COSTOS_MULTA.FECHAMODIFICACION IS 'Fecha de Modificación del Registro';
COMMENT ON COLUMN COSTOS_MULTA.OBSREGISTRO IS 'Observaciones del Registro';


